### ISSUE TITLE
Incorrect implementation of equals in ProxyQuantityFactory.GenericHandler.invoke()

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#104]
The implementation of equals checks whether the argument is an instance of AbstractQuantity, but that should be Quantity.

The implementation of hashCode() can be improved to use Objects.hash().

Also, some of the methods in the case clause are unreachable because they're not defined in the Quantity interface.

**Comment by keilw** [comment]
Do you see a way to fix these? I have to add, `ProxyQuantityFactory` is only a backup implementation, the default `ServiceProvider` does not use it and I cannot say, if there is any situation where it has a key benefit over `DefaultQuantityFactory`?

The way to get a new instance here requires the class, regardless which of he two are used. I don't see a quick way we could make both pluggable and interchangeable via `ServiceLoader` like the `*Service` implementations, do you? We could deprecate and remove it as well, but if there is value keeping it and it's easy to address, please do. An extension of `ServiceProvider` / `DefaultServiceProvider` would be free to override the method and use `ProxyQuantityFactory` or even its own implementation, so it is unused but not unusable.

**Comment by filipvanlaenen** [comment]
Pull request #105 contains a patch for the equals and hashCode methods.

**Comment by filipvanlaenen** [comment]
If there isn't a clear use case for this class, then I think it should be removed.

**Comment by keilw** [comment]
@desruisseaux What do you think about this? I know, you created it earlier for JSR 275 already. We took it over, but especially in uom-se @otaviojava myself and others took a slightly different approach, e.g. to avoid the overhead of Dynamic Proxies. Does SIS implement `QuantityFactory` already? It's only part of the SPI profile, so no need to do it, depending on which profiles an implementation wants to pass. SPI/Full profiles require a `QuantityFactory` implementation. Since you created it, I assume you could also take it over into Seshat under Apache license. Or is there another implementation already?

**Comment by desruisseaux** [comment]
SIS implements `QuantityFactory` using proxies, and the result of arithmetic operations is for example `Length` rather than `Quantity<Length>`. However I have not yet looked at the issue described here, so I'm not sure what the question is?

Regarding whether `equals` should check for `Quantity` instead than `AbstractQuantity`, it depends. The `Object.equals(Object)` javadoc explicitly requires that `A.equals(B) == B.equals(A)`. For making that possible with any `Quantity` implementation, we have to specify `equals` and `hashCode` behavior in `Quantity` javadoc (like what `java.util.List` and `Set` do for example). I don't think that we have done that, if I remember right. In the absence of specification in `Quantity` interface, checking for known implementation like `AbstractQuantity` is a conservative fallback for ensuring that `Object.equals(Object)` contract is respected.

**Comment by keilw** [comment]
I thought it checks for `Quantity` anyway, at least `testQuantityIsEqualToNumberQuantity` comparing the proxy result with that by the `Quantities` facade works. I think we're not yet in a position where different implementations like Indriya, Seshat or Eclipse UOMo could be mixed under a single classpath. So if similar or refined in SIS this proxy-based `QuantityFactory` exists there, could we remove it here for now?

**Comment by desruisseaux** [comment]
I'm not sure to understand. Remove what exactly?

On `AbstractQuantity.equals(Object)` checking for `AbstractQuantity` instead of `Quantity`: one problem is that we must comply to the following rule specified in `Object` javadoc:

* If `A.equals(B)`, then `A.hashCode()` == `B.hashCode()`

Complying to this rule (and some others) is necessarily for avoiding `HashMap` to behave erratically. But if A and B are not of the same implementation, then there is no guarantees that they compute their hash code in the same way, unless we document in `Quantity` javadoc how such hash code shall be computed. The problem is that `Quantity` hash code would probably depend on `Unit` hash code, which would need to be specified too, _etc._ down the dependency chain.

> I think we're not yet in a position where different implementations like Indriya, Seshat or Eclipse UOMo could be mixed under a single classpath.

This argument can be reversed: if implementations are not mixed, checking for `Quantity` instead of `AbstractQuantity` would not provide any gain (assuming all Indriya quantity implementations extend `AbstractQuantity`). But if implementations are mixed, then checking explicitly for `AbstractQuantity` reduce the risk of erratic `HashMap` behavior.

**Comment by keilw** [comment]
`ProxyQuantityFactory`. I don't see, why it has to be AbstractQuantity, although the result of `ProxyQuantityFactory.create()` also works for equality.

**Comment by filipvanlaenen** [comment]
I'm deferring the discussion about whether or not `ProxyQuantityFactory` should be removed to #106. Pull request #105 fixed the original issue, so therefore I close this one here.
