### ISSUE TITLE
Method BaseUnit#getBaseUnits returns null

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#180]
Guessing from its name, I would assume that a map should be returned, with `self` as a key and 1 as the value. I.e. a base unit is its own base unit with power 1.

**Comment by keilw** [comment]
This works as specified in the API. @filipvanlaenen if you believe, there is a value in having something other than null (the method in BaseUnit asks a question, too, Optional is a bad choice in Java 8 I'm afraid because it works bad with nested generics, but either the BaseUnit itself or an empty List might work, it does however require a redefinition in the API, so raise there if necessary)
