### ISSUE TITLE
ProductUnit.hashCode returns different results depending on the order of the elements

### ISSUE THREAD

**Issue by filipvanlaenen** [unitsofmeasurement/indriya#185]
The hashCode is based on the hashCode of the array with the elements, which means that the order plays a role. The elements should be sorted before producing the hashCode, such that kg·m and m·kg return the same hashCode.

**Comment by keilw** [comment]
Thanks, guess `equals()` and `hashCode()` of `CompoundUnit` are OK because there the order matters. One could argue that `4' 6"` or `6 h, 30 min, 10 s` should be equal to `6" 4'` or `30 min, 6h, 10 s`, but IMO here the order should matter as it is preserved when formatting a `CompoundQuantity` backed by such unit.

**Comment by filipvanlaenen** [comment]
Makes sense, but make sure to write that up in a unit test on the class and in the Javadoc so that it isn't forgotten.

Closing this issue as it is solved by pull request #186 .
