### ISSUE TITLE
How to serialize Quantities and Units?

### ISSUE THREAD

**Issue by andi-huber** [unitsofmeasurement/indriya#203]
What is the current best practice to serialize instances of `Quantity` to XML or JSON?

I suppose there could or should be a specific `Formatter` to cover this use case.

I'm also curious whether such a serialization format should be well documented and part of the JSR 385, to allow for users to serialize (and parse) instances of `Quantity` in a way, that is independent of the implementing library.

**Comment by keilw** [comment]
For JSON this is covered in https://github.com/unitsofmeasurement/uom-lib/tree/master/jackson already. Where you think of QuantityFormat or UnitFormat implementations, they could go there, but this is not something for the RI itself, will close this here because it is out of scope, please raise a ticket in https://github.com/unitsofmeasurement/uom-lib/issues for things like XML support or other JSON libraries like the JSONB standard.

**Comment by andi-huber** [comment]
I was not aware of these extension projects. Thx for the pointers.
