### ISSUE TITLE
Same Units considered different

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/indriya#3]
- [x] Create Wiki page
- [x] Copy/Move relevant portions of the Equality documentation to the [UoM Guide]
(https://github.com/unitsofmeasurement/uom-guide)
- [x] Mention this problem in the [Specification](https://docs.google.com/document/d/12KhosAFriGCczBs6gwtJJDfg_QlANT92_lhxUWO2gCY/), probably in a new chapter

See https://github.com/unitsofmeasurement/uom-se/issues/164

**Comment by keilw** [comment]
Related to https://github.com/unitsofmeasurement/indriya/issues/4

**Comment by andi-huber** [comment]
Proposed composition table, yielding a normal-form according to 
https://github.com/unitsofmeasurement/unit-api/issues/89

| NormalForm Order | Composition | POWER                                              | RATIONAL                                                                                    | MULTIPLY | PI_MUL | PI_DIV | ADD  | LOG  | EXP  |
|------------------|-------------|----------------------------------------------------|---------------------------------------------------------------------------------------------|----------|--------|--------|------|------|------|
| 1                | POWER       | If same base → POWER,  Else → CO(lower base first) | If RATIONAL represents (integer) base^exponent With same base as POWER → POWER,  Else → NFO | NFO      | NFO    | NFO    | COMP | COMP | COMP |
| 2                | RATIONAL    | #                                                  | RATIONAL                                                                                    | NFO      | NFO    | NFO    | COMP | COMP | COMP |
| 3                | MULTIPLY    | #                                                  | #                                                                                           | MULTIPLY | NFO    | NFO    | COMP | COMP | COMP |
| 4                | PI_MUL      | #                                                  | #                                                                                           | #        | COMP   | ID     | COMP | COMP | COMP |
| 5                | PI_DIV      | #                                                  | #                                                                                           | #        | #      | COMP   | COMP | COMP | COMP |
| 6                | ADD         | #                                                  | #                                                                                           | #        | #      | #      | ADD  | COMP | COMP |
| 7                | LOG         | #                                                  | #                                                                                           | #        | #      | #      | #    | COMP | ID   |
| 8                | EXP         | #                                                  | #                                                                                           | #        | #      | #      | #    | #    | COMP |

`#` ... Omitted due to symmetry
 
ID ... IDENTITY
POWER ... PowerConverter.class
RATIONAL ... RationalConverter.class
MULTIPLY ... MultiplyConverter.class
ADD ... AddConverter.class
LOG ... LogConverter.class
EXP ... ExpConverter.class
PI_MUL ... PiMultiplierConverter.class
PI_DIV ... PiDivisorConverter.class
 
COMP ... Non-Commutative (default) composition
CO ... Commutative composition with predefined order
NFO ... Commutative composition with NormalForm order (lower order first)

**Comment by keilw** [comment]
I would not see them as extensions to `PowerConverter` but `PiMultiplierConverter` does a lot similar to `MultiplyConverter`.

**Comment by andi-huber** [comment]
@keilw yes, these converters all represent multiplication. However, `PiMultiplierConverter` and `PiDivisorConverter` do know how to properly handle multiplication of BigDecimal with PI or 1/PI, which the `MultiplyConverter` does not.

To clarify what I'm aiming for is that composition of these Pi converters can be simplified eg
PI_MUL * PI_MUL * PI_MUL -> PI^3
PI_DIV * PI_DIV * PI_DIV -> PI^-3
PI_MUL * PI_MUL * PI_DIV * PI_DIV -> PI^0 = IDENTITY

**Comment by andi-huber** [comment]
I've updated the proposed composition table above.

**Comment by keilw** [comment]
Unfortunately 40 tests are failing, I disabled the class in question, because the Indriya build on master should not constantly fail. I personally don't have a problem with a name like `PiPowerConverter`, but the JavaDoc should say more about the "power" aspect, if it just reads "multiply by Pi" the name seems misleading.

**Comment by andi-huber** [comment]
Composition table (above) updated to reflect the current implementation.

**Comment by andi-huber** [comment]
Started a wiki page to document the background required for solving this issue.
https://github.com/unitsofmeasurement/indriya/wiki/Unit-Equivalence

**Comment by keilw** [comment]
Great, thanks. Some of that may eventually go either into the Spec or [UoM Guide Book](https://github.com/unitsofmeasurement/uom-guide).

**Comment by andi-huber** [comment]
Extending the corresponding wiki page with thoughts on _Simplification Rules_
https://github.com/unitsofmeasurement/indriya/wiki/Unit-Equivalence#simplification-rules

I conclude 2 things:

1. We need some kind of an 'intermediate normal-form' that keeps all information of the original transformations used for a composition, without loss of precision, so that we can do further compositions and simplifications properly. (That's the state of the current implementation, it yields such an intermediate  normal-form.)
2. We need a 'fully simplified normal-form' for actual calculus and test for equivalence. (Also applying simplification-rules as mentioned above.)

**Comment by andi-huber** [comment]
Wiki: Filling in the gaps ...

Explaining unit-converter equivalence:
https://github.com/unitsofmeasurement/indriya/wiki/Unit-Equivalence#decide-ability-of-equivalence

Explaining the 'normal-form' yielding algorithm:
https://github.com/unitsofmeasurement/indriya/wiki/Unit-Equivalence#implementing-a-normal-form-yielding-composition-algorithm

**Comment by keilw** [comment]
@andi-huber Is there any more work here or are the other bullet points also done?

**Comment by andi-huber** [comment]
We have implemented `Unit.equals` in RI according to the write-up https://github.com/unitsofmeasurement/indriya/wiki/Unit-Equivalence. 

The other bullet points are not done, not by me.

**Comment by keilw** [comment]
The part about the Specification is on the critical path towards 2.0 (https://www.bipm.org/en/about-us/ shows, there will be a critical maintenance of the site between April 19 and 23, I bet it has something to do with SI reforms and it's good to wait until after that before we finalize the sped and possibly update links that may have changed) 

The other tasks may also happen later if necessary.

**Comment by keilw** [comment]
Anything still open here?

**Comment by keilw** [comment]
Created https://github.com/unitsofmeasurement/uom-guide/issues/5 for item 2, closing this.
