### ISSUE TITLE
Quantities#getQuantity(CharSequence) doesn't work with Dimensionless quantities

### ISSUE THREAD

**Issue by daniel-shuy** [unitsofmeasurement/indriya#324]
According to the Javadoc of [Quantities#getQuantity(CharSequence)](https://javadoc.io/doc/tech.units/indriya/latest/tech/units/indriya/quantity/Quantities.html#getQuantity-java.lang.CharSequence-):
> This method can be used to parse dimensionless quantities. Quantity  proportion = Quantities.getQuantity("0.234").asType(Dimensionless.class); 

However, running `Quantities.getQuantity("0.234").asType(Dimensionless.class)` throws:
```
IllegalArgumentException: No Unit found
```

**Comment by andi-huber** [comment]
confirmed; 

Instead of using parsing, you could also write 
```java
import tech.units.indriya.AbstractUnit;
...
Quantity<Dimensionless> q = Quantities.getQuantity(0.234, AbstractUnit.ONE); 
```

**Comment by keilw** [comment]
@andi-huber Not sure if that's even a bug, the statement is completely correct, it's a number, not a quantity.

**Comment by andi-huber** [comment]
Hi @keilw - what do you mean, which statement is correct?

**Comment by keilw** [comment]
The `IllegalArgumentException` is correct, I see nothing wrong if you try to create a quantity without a unit there's an error. If it's not documented in the JavaDoc we might like to change that.

**Comment by andi-huber** [comment]
Ok, I'm agnostic to how we want to solve this, fixing code or fixing java-doc, both fine with me.

**Comment by daniel-shuy** [comment]
If the behavior is correct, then ideally the Javadoc should be updated to recommend using [AbstractQuantity#parse(CharSequence)](https://javadoc.io/static/tech.units/indriya/2.1.1/src-html/tech/units/indriya/AbstractQuantity.html#line.356) to parse dimensionless quantities

**Comment by keilw** [comment]
It is correct because `Quantities` also should allow to parse mixed quantities. There is merely an inconsistency between the two because they use exactly the same `SimpleUnitFormat` except configured differently.

**Comment by keilw** [comment]
It was as I thought, while `Quantities.getQuantity("1 m 70 cm")` works perfectly fine and converts to a sum of a `MixedQuantity`, calling `AbstractQuantity.parse("1 m 70 cm")` fails with a `MeasurementParseException`.
Since `AbstractQuantity` and `MixedQuantity` do not have the same parent for a good reason (`MixedQuantity` is more of a specialized `Collection` or array) we could leave it like that allowing the number without a unit to be parsed only by `AbstractQuantity` while `Quantities` recognizes mixed strings but it insists on a unit for that reason.

**Comment by daniel-shuy** [comment]
Thanks @keilw
