### ISSUE TITLE
Missing Names, Symbols in static instances

### ISSUE THREAD

**Issue by GregJohnStewart** [unitsofmeasurement/indriya#369]
There are a number of static units that are missing name and symbol values. I can probably go in and add them myself and make a PR, but wanted the consensus/ go-ahead from you guys first.

Examples (from the units I currently directly use):

- `Units.GRAM`
- ...

There are way more, seems like most of the ones I use are missing at least their symbol or name.

**Comment by GregJohnStewart** [comment]
Looking at the code, it seems to be the case that these are units that are derived from others

For instance, `GRAM` is a derivitave of `KILOGRAM`, and the `addUnit` method has no parameters to specify name or symbol.

Ostensibly these parameters will need added and used.

**Comment by andi-huber** [comment]
As far as I understand (I am not involved with the API design), methods ...
```
public interface Unit<Q extends Quantity<Q>> {

    // Returns the symbol (if any) of this unit. This method returns {@code null} if this unit has no specific symbol associated with.
    String getSymbol();

     // Returns the name (if any) of this unit. This method returns {@code null} if this unit has no specific name associated with.
    String getName();
//...
}
```
are both rather for framework internal use and probably only declared/needed on _base_ units. You usually need to resort to any of the built-in formatters in order to get human readable output for say `Units.GRAM`. Apparently `Units.GRAM.toString()` also works to get you at least the symbol 'g'.

Granted, this is not intuitive and Javadoc above is rather vague (but at least not wrong).

That said, if adding missing symbols and names does not break the framework, then I don't see any reason to not do it. Otherwise if it breaks the framework, we should at least clarify above Javadoc. 

I don't have enough insight into the formatting stuff, so I cannot give strong advice in any of these directions.

**Comment by keilw** [comment]
The name is rarely used and `addUnit()` has no purpose in `BasedUnit`, it is a method in `SystemOfUnits` implementations. 
As for the formatting, you more often get a combined result for units that are derived from others, therefore neither `getName()` nor `getSymbol()` are guaranteed to return something. They mostly do for the units added to the systems that are well-known, but you always can rely on `toString()`.

**Comment by GregJohnStewart** [comment]
I'm asking for them to be added, as my use case would greatly benefit from them all being present... `toString()` has proved not to be sufficient, and I'd rather not have to re-declare a bunch of static members to get this functionality.

To be clear, I am building a system that allows a user to choose their own units, and thus needs proper display of the name and symbol of the unit. `toString()` gets the point across, but is not enough.

I don't think this is a big ask, and this shouldn't be a hard thing to add in
