### ISSUE TITLE
Units.KILOMETRE is referenced in JavaDoc

### ISSUE THREAD

**Issue by alan-czajkowski** [unitsofmeasurement/indriya#370]
`Units.KILOMETRE` is referenced as an _existing_ unit here:
https://github.com/unitsofmeasurement/indriya/blob/master/src/main/java/tech/units/indriya/unit/Units.java#L482

but does not actually exist

probably need to define something like:
```java
public static final Unit<Length> KILOMETRE = KILO(METRE);
````

**Comment by keilw** [comment]
Yes it's a minor issue about the documentation, will fix it thanks for spotting, but unlike other unit systems (including https://github.com/unitsofmeasurement/uom-systems/tree/master/unicode) where these libraries (in this case [ICU4J](https://unicode-org.github.io/icu/userguide/icu4j/)) we do not expose all the possible combinations of prefixes here, so if you want a `KILOMETER` or `KILOMETRE` you'd have to use `CLDR` or define it in your own app.

**Comment by alan-czajkowski** [comment]
I don't think asking for a `KILOMETRE` is too much to ask, it is a very popular unit, unlike other *metre units, and if both `GRAM` and `KILOGRAM` are defined in the library it is safe to also define `METRE` and `KILOMETRE` (using the same justification)

I also found this bug with `GRAM`:

```java
System.out.println(GRAM);
System.out.println(GRAM.getName());
System.out.println(KILOGRAM);
System.out.println(KILOGRAM.getName());
```

produces:
```
g
null
kg
Kilogram
```

**Comment by keilw** [comment]
We might consider it in [systems-unicode](https://github.com/unitsofmeasurement/uom-systems/tree/master/unicode) where ICU4J also exposes lots of prefixes like `CENTILITER` or `GIGAHERTZ`, but we won't do it here.

**Comment by alan-czajkowski** [comment]
I really think my explanation and justification above warrant implementing the suggestions (they make sense).

What about the bugs I mentioned?

**Comment by alan-czajkowski** [comment]
@andi-huber I don't think the international standards affect the implementation of the library :)
I understand that **kilogram** is the base unit in SI, but that does not mean it should _not_ be implemented correctly within the library itself:
it should be defined as:
```java
public static final Unit<Mass> KILOGRAM = addUnit(KILO(GRAM));
```
instead of:
```java
public static final Unit<Mass> KILOGRAM = addUnit(new BaseUnit<Mass>("kg", "Kilogram", UnitDimension.MASS), Mass.class);
```

and this would still satisfy the desire to have the international base unit pre-defined in the library :)

**Comment by keilw** [comment]
@alan-czajkowski In case of `KILOGRAM` that would be wrong, it is perfectly fine 
```
public static final Unit<Mass> KILOGRAM = addUnit(new BaseUnit<Mass>("kg", "Kilogram", UnitDimension.MASS), Mass.class);
```
The kilogram is a base unit and the proposed declaration would destroy that, so @andi-huber please do not change anything there.
`GRAM` is the only exception, strictly speaking it should not be there but UCUM also defines it (see https://ucum.org/ucum.html#section-Base-Units that is a breach with the SI System and Indriya is consistent with SI here, while offering the bridge to UCUM here. Everything else is not declared in UCUM either, there are no constants like `MILLIMETER`, `MILLIGRAM`, etc. that is why we should not clutter the RI because the prefixes exist in the API and may be combined with every given unit. ICU4J is redundant because it also added a [MeasurePrefix](https://unicode-org.github.io/icu-docs/apidoc/dev/icu4j/index.html?com/ibm/icu/util/MeasureUnit.MeasurePrefix.html) enum a lot later, but that cannot be directly combined with the units, therefore it defined the likes of `MILLILITER` or `MILLIMETER`, but it only contains OHM and not `MILLIOHM` although there are [measuring devices](https://www.instrumart.com/categories/5979/milliohm-meters#:~:text=Milliohm%20and%20micro%2Dohm%20meters,one%20millionth%20of%20an%20ohm) going down to that or even `MICROOHM`.

**Comment by alan-czajkowski** [comment]
@keilw your mind is still stuck on the idea that the SI standards drive the underlying library implementation ... but these are completely distinct concerns that do not need to be mixed ... pre-defining GRAM inside of the library, in order to correctly use the KILO() modifier does not violate your desire to have the library have pre-defined standard base units
the fact that the library has
GRAM
and
KILO(GRAM)
where GRAM is an "extra" (non-standard) unit pre-defined in the library, does no harm to the library whatsoever

**Comment by keilw** [comment]
I also changed the title, the reason this ticket is open is just to clean that JavaDoc leftover (from a time when UCUM was part of the RI) so @andi-huber or others please feel free to fix the JavaDoc glitch, but do not tamper with the definition of `BaseUnit`s

**Comment by desruisseaux** [comment]
Indeed on a conceptual point of view, `KILOGRAM` is a base unit. It may be tempting to deviate from the international standard for implementation convenience, but while it brings _internal_ consistency (i.e. consistency of the library with itself) it would also brings _external_ inconsistency (i.e. inconsistency with the world outside the implementation). Base units play a role not only for reading/writing unit symbols, but also in domains like dimensional analysis. So I think that "cheating" there would be the kind of risk that the JSR project wanted to avoid.

However it should be possible to keep base units standard compliant, and still have expressions such as `KILO(GRAM) == KILOGRAM` to behave as expected (maybe it is already the case? I didn't tried). It is harder on an implementation point of view, but it should be possible to have the implementation do some magic if necessary. So maybe we could rephrase this issue as what could be improved without deviating from the international standard?

**Comment by keilw** [comment]
We have an expression of `assertTrue(KILO(GRAM).isEquivalentTo(KILOGRAM))` Because of Java's strict type-safety the notion of "equivalence" was introduced so it also works the same for "1000 g" or "1000 m" compared to `KILO(METRE)`.

**Comment by keilw** [comment]
Thanks for the input everyone. I fixed the JavaDoc and will close this ticket now.
Regarding the `getName()` method there were also several hints how to use it. Generally every `BaseUnit` is supposed to have a name and symbol, while transformed or otherwise derived units often don't have a symbol by definition. Their visual representation is influenced via the label (in `UnitFormat`). Both symbol and name are immutable on an API level, so the only way to apply a name is the internal "SPI" of `AbstractSystemOfUnits`. 

Many declarations in `CLDR` and other subclasses of that abstract base class show how to do that.
Everyone is welcome to contribute more especially in the open source extension libraries (while here and in other parts of the JSR there is the need to at least join the JCP as an Associate member) or [demos](https://github.com/unitsofmeasurement/uom-demos).

**Comment by andi-huber** [comment]
I agree with Werner and Martin and I would not change the declaration of
```java
public static final Unit<Mass> KILOGRAM = addUnit(new BaseUnit<Mass>("kg", "Kilogram", UnitDimension.MASS), Mass.class);
```
either. Simply because of the very definition of `BaseUnit`:

> This class represents the building blocks on top of which all others physical units are created. Base units are always unscaled SI units.
