### ISSUE TITLE
 Use exception catching, possibly unnecessary performance overhead

### ISSUE THREAD

**Issue by fengyizhu** [unitsofmeasurement/indriya#387]
tech.units.indriya.function.DefaultNumberSystem#narrow

```
        if(number instanceof BigDecimal) {
            
            final BigDecimal decimal = ((BigDecimal) number);
            try {
                BigInteger integer = decimal.toBigIntegerExact(); 
                return narrow(integer);
            } catch (ArithmeticException e) {
                return number; // cannot narrow to integer
            }
        }
```
why not just return BigDecimal？

**Comment by fengyizhu** [comment]
<img width="2549" alt="image" src="https://user-images.githubusercontent.com/14803325/201644596-7862e58c-b928-4b87-9c64-c0f12e84b8b5.png">

**Comment by keilw** [comment]
@fengyizhu What does this graph show, and is there a test suite you can share to replicate?

@andi-huber What was the `BigInteger` extraction done there? I understand `isIntegerOnly()` check simply does a Java type check, but why not apply `isInteger()` or try reuse the  `if(decimal.scale()<=0)` bit instead of trying the exception first?

**Comment by fengyizhu** [comment]
#388

**Comment by fengyizhu** [comment]
@keilw Please See #388

**Comment by andi-huber** [comment]
Indeed, producing stacktraces just to do a check is costly. I merged https://github.com/unitsofmeasurement/indriya/pull/388

see also https://stackoverflow.com/questions/1078953/check-if-bigdecimal-is-an-integer-in-java

**Comment by keilw** [comment]
The scope is here: https://github.com/unitsofmeasurement/indriya/milestone/10 but there's not a concrete time.
